version: '3.8'

services:

  install:
    image: node:21.4-alpine3.17
    user: node
    working_dir: /home/node/app
    volumes:
      - ./:/home/node/app
    command: npm install

  lint:
    image: node:21.4-alpine3.17
    user: node
    working_dir: /home/node/app
    volumes:
      - ./:/home/node/app
    command: npm run lint

  build:
    image: node:21.4-alpine3.17
    user: node
    working_dir: /home/node/app
    volumes:
      - ./:/home/node/app
    command: npm run build

  build-dev:
    image: node:21.4-alpine3.17
    user: node
    working_dir: /home/node/app
    volumes:
      - ./:/home/node/app
    command: npm run build-dev

  test:
    image: node:21.4-alpine3.17
    user: node
    working_dir: /home/node/app
    volumes:
      - ./:/home/node/app
    command: npm test
