name: Test

on:
  push:
    branches:
      - 'issue-**'
      - develop
  pull_request:
    branches:
      - main

env:
  NODE: 21.4

jobs:
  test:
    runs-on: ubuntu-latest

    steps:
      - name: Clone repository
        uses: actions/checkout@v2

      - name: Set up Node.js
        uses: actions/setup-node@v2
        with:
          node-version: "${{ env.NODE }}"
          cache: npm

      - name: Install npm dependencies
        run: npm ci

      - name: Build
        run: npm run build

      - name: Test
        run: npm test
